---
# /nextcloud-ansible/roles/nginx/tasks/main.yml

- name: Создаем директорию
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Добавляем Kubernetes GPG key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
    force: yes
  become: yes
  register: gpg_key

- name: De-armor GPG key
  command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: yes
  when: gpg_key.changed

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes
  become: yes

- name: Снять hold с пакетов Kubernetes
  dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: yes

- name: Ставим пакеты
  ansible.builtin.apt:
    name:
      - docker.io
      - ca-certificates
      - apt-transport-https
      - curl
    state: present
    update_cache: yes
  become: yes

- name: Ставим пакеты k8s
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes
  become: yes

- name: Запрет автообновления пакетов
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  become: yes

- name: Ставим Докер в автозапуск
  service:
    name: docker
    enabled: yes
  become: yes

- name: Включаем Докер
  service:
    name: docker
    state: started
  become: yes
