apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pvc
  namespace: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
