apiVersion: apps/v1  # Версия API для StatefulSet.
kind: StatefulSet  # Тип: StatefulSet для stateful приложений.
metadata:
  name: postgres  # Имя.
  namespace: mediawiki  # Namespace.
spec:
  serviceName: postgres  # Имя сервиса для StatefulSet.
  replicas: 1  # Количество реплик (1 для простоты).
  selector:
    matchLabels:
      app: postgres  # Селектор для подов.
  template:
    metadata:
      labels:
        app: postgres  # Лейблы подов.
    spec:
      containers:
      - name: postgres  # Имя контейнера.
        image: postgres:15  # Официальный image PostgreSQL (версия 15).
        env:
        - name: POSTGRES_PASSWORD  # Переменная окружения: пароль.
          valueFrom:
            secretKeyRef:
              name: postgres-secret  # Из секрета.
              key: postgres-password  # Ключ.
        - name: POSTGRES_DB  # Имя БД.
          value: mediawiki  # Значение: mediawiki.
        - name: POSTGRES_USER  # Пользователь БД.
          value: mediawiki_user  # Значение (можно изменить).
        ports:
        - containerPort: 5432  # Порт БД.
        resources:  # Ресурсы.
          requests:  # Запросы (минимальные).
            memory: "512Mi"  # 512 МБ памяти.
            cpu: "500m"  # 0.5 CPU.
          limits:  # Лимиты (максимальные).
            memory: "1Gi"  # 1 ГБ памяти.
            cpu: "1"  # 1 CPU.
        livenessProbe:  # Проба живучести: проверка, жив ли контейнер.
          exec:
            command: ["pg_isready", "-U", "mediawiki_user"]  # Команда: проверка готовности БД.
          initialDelaySeconds: 30  # Задержка перед первой проверкой.
          periodSeconds: 10  # Интервал проверок.
        readinessProbe:  # Проба готовности: готов ли принимать трафик.
          exec:
            command: ["pg_isready", "-U", "mediawiki_user"]  # Аналогично.
          initialDelaySeconds: 5  # Задержка.
          periodSeconds: 5  # Интервал.
        volumeMounts:  # Монтирование volume.
        - mountPath: /var/lib/postgresql/data  # Путь в контейнере.
          name: postgres-storage  # Имя volume.
  volumeClaimTemplates:  # Шаблон PVC для StatefulSet.
  - metadata:
      name: postgres-storage  # Имя.
    spec:
      accessModes: ["ReadWriteOnce"]  # Режим.
      resources:
        requests:
          storage: 5Gi  # Размер.
      storageClassName: local-storage  # Класс.
---
apiVersion: v1  # Версия API для Service.
kind: Service  # Тип: Service.
metadata:
  name: postgres  # Имя.
  namespace: mediawiki  # Namespace.
spec:
  selector:
    app: postgres  # Селектор подов.
  ports:
  - port: 5432  # Порт сервиса.
    targetPort: 5432  # Порт в поде.
  clusterIP: None  # Headless сервис для StatefulSet.